/*
 * Generated by go-libtor's wrapper.
 */

#ifndef OPENSSL_OPENSSLV_H
#define OPENSSL_OPENSSLV_H
#pragma once

#ifdef __cplusplus
extern "C" {
#endif

#define OPENSSL_VERSION_MAJOR 3
#define OPENSSL_VERSION_MINOR 6
#define OPENSSL_VERSION_PATCH 1
#define OPENSSL_VERSION_PRE_RELEASE ""
#define OPENSSL_VERSION_BUILD_METADATA ""
#define OPENSSL_SHLIB_VERSION 3
#define OPENSSL_VERSION_PREREQ(maj, min) \
    ((OPENSSL_VERSION_MAJOR << 16) + OPENSSL_VERSION_MINOR >= ((maj) << 16) + (min))
#define OPENSSL_VERSION_STR "3.6.1"
#define OPENSSL_FULL_VERSION_STR "3.6.1"
#define OPENSSL_RELEASE_DATE "27 Jan 2026"
#define OPENSSL_VERSION_TEXT "OpenSSL 3.6.1 27 Jan 2026"
#define OPENSSL_VERSION_NUMBER          \
    ( (OPENSSL_VERSION_MAJOR<<28)        \
      |(OPENSSL_VERSION_MINOR<<20)       \
      |(OPENSSL_VERSION_PATCH<<4)        \
      |0x0L )

#ifdef __cplusplus
}
#endif

#endif
